name: build-devsecops.yml

on:
    push:
        branches:
            - dev
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    security:
        runs-on: ubuntu-latest
        name: security
        steps:
            - uses: actions/checkout@v3
            - uses: DigitalIDF/Cloud-Security-Task@v1
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
