name: build-deploy-invalidate-cache-action
on:
    workflow_call:
        inputs:
            environment_name:
                description: 'Docker environment name'
                required: true
                type: string
            docker_build_context:
                description: 'Docker build context'
                required: true
                type: string
            docker_image_name_suffix:
                description: 'Docker image name suffix'
                required: true
                type: string
            k8s_namespace:
                description: 'Kubernetes namespace'
                required: true
                type: string
            k8s_deployment:
                description: 'Kubernetes Deployment name'
                required: true
                type: string
            runner_name:
                description: 'Workflow Runner Name'
                required: true
                type: string
        secrets:
            AWS_CLOUDFRONT_DISTRIBUTION_ID:
                description: 'AWS CloudFront Distribution ID'
                required: true

jobs:
    build-tag-push:
        runs-on: ubuntu-latest
        environment: ${{ inputs.environment_name }}
        steps:
            - name: Checkout branch
              uses: actions/checkout@v3

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Get repository name as lower case string
              id: string
              uses: ASzc/change-string-case-action@v5
              with:
                  string: ${{ github.repository }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v3
              with:
                  context: ${{ inputs.docker_build_context }}
                  push: true
                  tags: |
                      ghcr.io/${{ steps.string.outputs.lowercase }}/${{ inputs.environment_name }}:${{ github.sha }}
                                ghcr.io/${{ steps.string.outputs.lowercase }}/${{ inputs.environment_name }}:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

    deploy:
        needs: build-tag-push
        runs-on: [self-hosted, aws, ec2runner, '${{ inputs.runner_name }}']
        environment: ${{ inputs.environment_name }}

        steps:
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  aws-region: eu-west-1
                  role-duration-seconds: 3600

            - name: Rollout deployment restart
              run: |
                  kubectl rollout restart deployment ${{ inputs.k8s_deployment }} --namespace ${{ inputs.k8s_namespace }}

            - name: Invalidate CloudFront cache
              run: |
                  aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
