name: Trigger Services Workflow

on:
  workflow_dispatch:
  
jobs:
  trigger-services:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Service Workflows
        run: |
          echo "Triggering service workflows..."
          
          # Trigger Service 1 Workflow
          - name: Trigger Service 1
            run: |
              gh workflow run build-deploy-refresh-cache-server.yaml

          # Trigger Service 2 Workflow
          - name: Trigger Service 2
            run: |
              gh workflow run build-devsecops-server.yaml -n service2 

          # Trigger Service 3 Workflow
          - name: Trigger Service 3
            run: |
              gh workflow run cicd-dev-server.yaml -n service3 

          # Trigger Service 4 Workflow
          - name: Trigger Service 4
            run: |
              gh workflow run cicd-preprod-server.yml 

          echo "Service workflows triggered."
