name: Trigger Client Workflow

on:
  workflow_dispatch:
  
jobs:
  trigger-services:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Client Workflows
        run: |
          echo "Triggering Client workflows..."
          
          # Trigger Service 1 Workflow
          - name: Trigger Service 1
            run: |
              gh workflow run build-deploy-refresh-cache-client.yaml

          # Trigger Service 2 Workflow
          - name: Trigger Service 2
            run: |
              gh workflow run build-devsecops-client.yaml -n service2 

          # Trigger Service 3 Workflow
          - name: Trigger Service 3
            run: |
              gh workflow run cicd-dev-client.yaml -n service3 

          # Trigger Service 4 Workflow
          - name: Trigger Service 4
            run: |
              gh workflow run cicd-preprod-client.yml 

          echo "Service workflows triggered."
