# this file will point to another file containing the flows needed for the change
name: Trigger workflows based on change 

on:
  push:
    paths:
      - 'my-server-code/'  # Change to your server code directory path Asaf!!
      - 'my-client-code/'  # Change to your client code directory path Asaf!!

jobs:
  trigger-server-or-client-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Server or Client Workflows
        if: ${{ github.event.repository.owner == 'yourusername' }} #add the owner username
        run: | #notice to change the file names down here and later
          if [[ -n $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '#######/') ]]; then
            echo "Changes detected in the '########/' directory. Triggering server workflows..." 
            - name: Trigger Server Workflows
              run: |
                gh workflow run server-workflows-trigger.yaml -n server_workflow -r yourusername/your-repo    #####also change here
            echo "Server workflows triggered."
          fi

          if [[ -n $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'my-client-code/') ]]; then
            echo "Changes detected in the 'my-client-code/' directory. Triggering client workflows..."
            - name: Trigger Client Workflows
              run: |
                gh workflow run client-workflows-trigger.yaml -n client_workflow -r yourusername/your-repo
            echo "Client workflows triggered."
          fi
