# this file will point to another file containing the flows needed for the change
name: Trigger workflows based on change 

on:
  push:
    paths:
      - 'Server/**'  
      - 'Client/**'  

jobs:
  trigger-server-or-client-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Server or Client Workflows
        run: |
          if [[ -n $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'Server/**') ]]; then
            echo "Changes detected in the 'Server/**' directory. Triggering server workflows..." 
            - name: Trigger Server Workflows
              run: |
                gh workflow run Server/workflows/server-workflows-trigger.yaml
            echo "Server workflows triggered."
          fi

          if [[ -n $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'Client/**') ]]; then
            echo "Changes detected in the 'CLient/**' directory. Triggering client workflows..."
            - name: Trigger Client Workflows
              run: |
                gh workflow run Client/workflows/client-workflows-trigger.yaml
            echo "Client workflows triggered."
          fi
