name: Check Changes in Client/Server

on:
  push:
    paths:
      - 'Server/**'
      - 'Client/**'

env:
  GH_TOKEN: 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

jobs:
  check-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Get changed directories
        id: changes
        run: |
          echo "CHANGED_DIRECTORIES=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/DigitalIDF/MyNet/commits/${{ github.sha }}" | \
            jq -r '.files[] | select(.filename | startswith("Client/") or startswith("Server/")) | .filename | capture("^(?<directory>Client|Server)") | .directory' | sort -u)" >> "$GITHUB_ENV"
          echo "Changed directories: $CHANGED_DIRECTORIES" # For debugging purposes


      - name: Debug Changed Directories
        run: |
          echo "CHANGED_DIRECTORIES: $CHANGED_DIRECTORIES"

      - name: Check for Client Changes and trigger workflows
        if: ${{ env.CHANGED_DIRECTORIES == 'Client' }}
        run: |
          echo "Changes detected in the Client directory" 
          cd Client
          gh workflow run Client/workflows/client-workflows-trigger.yaml
      - name: Check for Server Changes and trigger workflows
        if: "contains('$CHANGED_DIRECTORIES', 'Server')"
        run: |
          echo "Changes detected in the Server directory"
          cd Server
          gh workflow run Server/workflows/server-workflows-trigger.yaml